package ch.chris.schichtensystem.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;

@Entity
@Table(name = "shift")
public class Shift {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @NotBlank(message = "shiftid cannot be blank")
    private String shiftid;

    @NotBlank(message = "date cannot be blank")
    private String date;

    @NotBlank(message = "text cannot be blank")
    private String text;

    public Shift() {
        // Default constructor
    }

    // Other constructors if needed

    public int getId() {
        return id;
    }

    // No setId method, as the ID is generated by the database

    public String getShiftid() {
        return shiftid;
    }

    public void setShiftid(String shiftid) {
        this.shiftid = shiftid;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

	public void setId(int id2) {
		// TODO Auto-generated method stub
		
	}
}
